name: Test Python Version

on:
  workflow_dispatch:  # manual trigger

jobs:
  check-python:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Show Python version
        run: python --version
